version: '3.8'

services:
  fish-speech-dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: fish-speech
    volumes:
      - ./:/exp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: "all"
              capabilities: [gpu]
              device_ids: ["1"]
    command: tail -f /dev/null
